apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: plexdash

resources:
  - base/namespace.yaml
  - base/cnpg-cluster.yaml
  - base/frontend-configmap.yaml
  - base/backend-deployment.yaml
  - base/frontend-deployment.yaml
  - base/ingress.yaml

commonLabels:
  app.kubernetes.io/name: plexdash
  app.kubernetes.io/managed-by: kustomize
